### ISSUE TITLE
M1 Macbook air

### ISSUE THREAD

**Issue by imustd** [PromtEngineer/localGPT#102]
Following steps 3 and 4 in the M1/M2 Macbook users section. Errors were generated in installing `xformers and cchardet`. (Hence) I couldn't find `instructor.py` 
There is no `InstructorEmbedding` directory  in `site-packages`

<img width="1369" alt="image" src="https://github.com/PromtEngineer/localGPT/assets/98457540/2579bba1-57b8-4144-a40f-2f93602ef336">
<img width="1371" alt="image" src="https://github.com/PromtEngineer/localGPT/assets/98457540/499158c9-5d69-4916-b21f-5dca8df1097f">

**Comment by johnm-starling** [comment]
It could possibly be in a path like this 

```
/System/Volumes/Data/opt/homebrew/lib/python3.11/site-packages/InstructorEmbedding/instructor.py
/System/Volumes/Data/opt/homebrew/anaconda3/envs/localgpt/lib/python3.10/site-packages/InstructorEmbedding/instructor.py

```


If you are using homebrew.
