### ISSUE TITLE
Provide CPU only how-to and implement an easy CPU only option

### ISSUE THREAD

**Issue by menelic** [PromtEngineer/localGPT#12]
Due to choice of both encoders and LLM your implementation has benefits over private GPT beyond GPU vs CPU usage ( as you explain here https://github.com/PromtEngineer/localGPT/issues/7#issuecomment-1566207689 ), and someone has apparently been able to make it run in CPU mode: See this comment under your helpful youtube video https://www.youtube.com/watch?v=MlyoObdIHyo

![image](https://github.com/PromtEngineer/localGPT/assets/5934115/f4b9fe11-35a3-425c-bb92-dafd893b9600)

Please provide a how to for running localGPT in CPU mode. Please consider an easily accessible CPU only option. I am aware of #6 but think this goes beyond whats discussed there

**Comment by PromtEngineer** [comment]
Added support for CPU. Now you can select a cpu by using the --device_type flag with value of cpu

`python ingest.py --device_type cpu`

& 

`python run_localGPT.py --device_type cpu`
