### ISSUE TITLE
Use GitHub Actions and Pre-commit

### ISSUE THREAD

**Issue by AhmedHathout** [PromtEngineer/localGPT#133]
I was thinking since there are many pull requests from many people, it is probably a good idea to set up GitHub Actions. One of the jobs can be to run pre-commit to make sure all conventions are met. GitHub actions will also be very useful (almost necessary) when there are some automated tests

**Comment by AhmedHathout** [comment]
I think I can work on this one myself today

**Comment by PromtEngineer** [comment]
Great idea, Thanks will appreciate that.
