### ISSUE TITLE
python ingest.py gets stuck on "load INSTRUCTOR_Transformer"

### ISSUE THREAD

**Issue by mindwellsolutions** [PromtEngineer/localGPT#17]
After running pip install -r requirements.txt and putting a new pdf into the source_documents folder. I ran python ingest.py . The first time it installed additional reequipments **but got stuck at "load INSTRUCTOR_Transformer"**

Here is a full screen shot.

![image](https://github.com/PromtEngineer/localGPT/assets/38707551/12038d9f-d582-4c92-a5fa-8476e702c180)

**Comment by PromtEngineer** [comment]
How big is the document? If you are running the CPU version, then it will take a while.

**Comment by mindwellsolutions** [comment]
Thank you, your solution worked. Once I ran it on a machine with an RTX 3080 it got past that step finally. However now I get a "Killed" error.

load INSTRUCTOR_Transformer
max_seq_length 512
Using embedded DuckDB with persistence: data will be stored in: /mnt/6903a017-f604-4f90-9652-324e10b3e675/work/h2oai/localgpt/localGPT
Loading checkpoint shards: 0%| | 0/2 [00:00<?, ?it/s]
Killed
