### ISSUE TITLE
Download models via corporate proxy not doable

### ISSUE THREAD

**Issue by bettercallcaleb** [PromtEngineer/localGPT#220]
hi team, I am having some difficulty downloadinging the models. if i download manually and place the model files in .cache with blobs/snapshots/refs, run_localGPT.py still going through huggingface website which is not doable. can we ignore the downloading part and use local files? figured out a way to do it. thanks

**Comment by parmou** [comment]
@bettercallcaleb did it work by downloading the model files manually?
