### ISSUE TITLE
Support for Llama 2

### ISSUE THREAD

**Issue by dzyla** [PromtEngineer/localGPT#235]
Hi, 

I tried to use the newest llama2 models from https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML, but I always get that the auto tokenizer cannot be found. Is there a trick to using the new model with LocalGPT?

Thanks,

**Comment by PromtEngineer** [comment]
I have tested it and it seems to work file. Here is the configuration I am using:
```

  model_id="TheBloke/Llama-2-7B-Chat-GGML"
   model_basename = "llama-2-7b-chat.ggmlv3.q4_0.bin"
```

Make sure you provide both the model_id and the basename.

**Comment by SaraiQX** [comment]
Hi master, wonder if TheBloke/Llama-2-70B-chat-GPTQ is supported by this amazing project? Thanks.

**Comment by sauravm8** [comment]
If you can load it on 1 GPU it will definitely work. Trying to get it to work on multiple GPUs rn.
