### ISSUE TITLE
Memory pooling across multiple GPUs 

### ISSUE THREAD

**Issue by ammorcos** [PromtEngineer/localGPT#294]
Is there anyway to use memory pooling to load larger models. I have 2 RTX 2070 super (old, I know) but keep running out of memory

**Comment by KonradHoeffner** [comment]
I would be very interested in this as well, as one of our servers has several RTX 2080s.

**Comment by ammorcos** [comment]
@sauravm8 I am not sure I follow what you mean. It looks like it still only uses one GPU when I remove device="cuda:0", from the AutoGPTQForCausalLM.from_quantized call. Can you please elaborate?

**Comment by ammorcos** [comment]
> If you have more than one device, do not specify cuda:0 while you are trying to load the model.

Thank you that did the trick
