### ISSUE TITLE
[Feature request] Include chat context

### ISSUE THREAD

**Issue by andypotato** [PromtEngineer/localGPT#314]
Currently the current chat context is not considered. So asking follow-up questions will fail like in this example:
```
Q: Who is the president of the USA?
A: The President of the United States is currently Joe Biden.

Q: When was he elected?
A: The text does not mention anything about when John F. Kennedy was elected.
```

How could we add the current chat context?

**Comment by PromtEngineer** [comment]
@andypotato this was added in #324. Closing it.
