### ISSUE TITLE
Bad performance and quality of answers

### ISSUE THREAD

**Issue by vitalykarasik** [PromtEngineer/localGPT#326]
Many thanks - I was able to install localGPT and ingest my docs. 
Two questions (vanilla install by cloning your repo as is, with TheBloke/Llama-2-7B-Chat-GGML model): 
1) on 16CPUs/64GB RAM x86 instance it takes 1-1.5 minutes for getting answer (w/o GPU)
2) "what is the term limit of the us president?" I'm getting "The President of the United States has a term limit of four years as specified in Article II, Section 1 of the US Constitution." answer :-(
When I'm asking about my documents, I'm getting low-quality answers.

Should I try another model? If so, which? Or tweak some params?

Thanks, Vitaly

**Comment by bettercallcaleb** [comment]
Using: models--TheBloke--WizardLM-7B-uncensored-GPTQ
Result: 
> Question:
what is the term limit of the us president?

> Answer:
 The term limit of the US President is two terms, as specified in Amendment XXII.

Enter a query:

**Comment by vitalykarasik** [comment]
Thank you, I'll try models--TheBloke--WizardLM-7B-uncensored-GPTQ,
Vitaly

**Comment by PromtEngineer** [comment]
@vitalykarasik What are the GPU resource usage? 
The quality of the answers will depend on both the LLM you select as well as the Embeddings model that you have. You will have to experiment with them to get the best results.

**Comment by vitalykarasik** [comment]
> @vitalykarasik What are the GPU resource usage? The quality of the answers will depend on both the LLM you select as well as the Embeddings model that you have. You will have to experiment with them to get the best results.

Thank you! 
I ran it without GPU. Does GPU may affect the quality of answers, not just performance?
Regarding "Embeddings model" - do you mean LLM model like Llama-2-7B-Chat-GGML?
