### ISSUE TITLE
Using cuda calculations, the GPU load is only a short time

### ISSUE THREAD

**Issue by lostmaniac** [PromtEngineer/localGPT#355]
The model used is: TheBloke/Llama-2-7B-Chat-GGML
localgpt version: latest
GPU: 3090 24G *2
python version: 3.10.9

Code modification:
kwargs["n_gpu_layers"] = 100000000000000000

After entering the question, according to the nvidia-smi command monitoring, the GPU only participated in the calculation for a short time, and then the CPU usage was very high. will keep waiting.

How to configure to use only GPU for calculation?

**Comment by lostmaniac** [comment]
|   0  NVIDIA GeForce ...  On   | 00000000:AF:00.0 Off |                  N/A |
| 30%   38C    P2   108W / 350W |   2316MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |

cuda 11.7

**Comment by ritwikagrawal1228** [comment]
Similar issue. Running the localgpt shows:

Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda

But stills CPU (as seen on task manager)

**Comment by lostmaniac** [comment]
found the solution:
CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python
