### ISSUE TITLE
move chunk_size and  chunk_overlap definitions into constants?

### ISSUE THREAD

**Issue by alexfilothodoros** [PromtEngineer/localGPT#382]
Hi,

@PromtEngineer 
Just a suggestion. Maybe it would be more practical to move the chunk_size and  chunk_overlap into the constants script.
During experimentation with various texts I noticed that I had to change these two settings and since they are constants, maybe it'd be better to move them to the corresponding file.

That's just a small suggestion.

**Comment by bp020108** [comment]
@alexfilothodoros - Can you please provide updated files to move chunk_size and overlap into constant. Or please let me know what are changes in both file? 

Is it helping on ingest time?

**Comment by alexfilothodoros** [comment]
Hi @bp020108 

It sure is affecting the ingesting time, bepending if you increase/decrease their values.
For it is just easier to have then in "constants.py" when I am experimenting with them.

I will provide the changes.

Cheers

**Comment by bp020108** [comment]
Thanks, Please provide changes once ready. Will test and let you know,
