### ISSUE TITLE
The -S option of privategpt is missing

### ISSUE THREAD

**Issue by lelapin123** [PromtEngineer/localGPT#4]
A way to not be spammed with sources and other texts that hides the answer

**Comment by PromtEngineer** [comment]
I will add flag for it.

**Comment by imjwang** [comment]
Hi @PromtEngineer are you welcome to contributors? I'd love to help out with this project

**Comment by PromtEngineer** [comment]
@imjwang Yes, that would be great.

**Comment by PromtEngineer** [comment]
The option has been added.
