### ISSUE TITLE
Warning: CUDA extension not installed

### ISSUE THREAD

**Issue by hedgar2017** [PromtEngineer/localGPT#402]
I have a warning that some CUDA extension is not installed, though localGPT works fine.

`2023-08-23 13:49:27,776 - WARNING - qlinear_old.py:16 - CUDA extension not installed.`

Is it something important about my installation, or should I ignore it?

I've using two NVIDIA GTX 1080 under Arch WSL on Windows.

**Comment by rcantada** [comment]
Assuming that cuda-toolkit, cudnn, etc are available, try to reinstall auto-gptq from source:

`pip uninstall -y auto-gptq`
`GITHUB_ACTIONS=true pip install auto-gptq==0.2.2 --no-cache-dir`

**Comment by hedgar2017** [comment]
> Assuming that cuda-toolkit, cudnn, etc are available, try to reinstall auto-gptq from source:
> 
> `pip uninstall -y auto-gptq` `GITHUB_ACTIONS=true pip install auto-gptq==0.2.2 --no-cache-dir`

Thanks! Tried this but I'm getting an error saying my CUDA is too new:
```
        File "/home/hedgar/.conda/envs/localGPT-Bandera/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.2) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for auto-gptq
  Running setup.py clean for auto-gptq
Failed to build auto-gptq
ERROR: Could not build wheels for auto-gptq, which is required to install pyproject.toml-based projects
```
Are the latest drivers unsupported?

**Comment by rcantada** [comment]
I have not tried building auto-gptq==0.2.2 with cuda 12
But your log says the mismatch is between your cuda-toolkit (12.2) and pytorch (appears to be built with 11.7)
The pytorch install matrix at https://pytorch.org/ only has installation instructions for cuda 11.8 at best.
You would have to compile and rebuild pytorch from source against cuda 12 to resolve the mismatch but I do not know how to do that. See https://discuss.pytorch.org/t/pytorch-for-cuda-12/169447

Or lower your cuda-toolkit to 11.8, (and perhaps match it with the appropriate cudnn that pytorch for cuda 11.8 comes with) and build around that.

**Comment by markjlorenz** [comment]
I had the same set of issues and was able to resolve them (and also significantly speed up response times) by:

```
pip uninstall -y auto-gptq
pip install auto-gptq --no-cache-dir
```

which installed a mucher newer version of auto-gptq than is specified in requirements.txt (`0.4.2` up from `0.2.2`).  It also came with pre-built wheel for the CUDA 11.5 that was installed on my system.

**Comment by hedgar2017** [comment]
> I had the same set of issues and was able to resolve them (and also significantly speed up response times) by:
> 
> 
> 
> ```
> 
> pip uninstall -y auto-gptq
> 
> pip install auto-gptq --no-cache-dir
> 
> ```
> 
> 
> 
> which installed a mucher newer version of auto-gptq than is specified in requirements.txt (`0.4.2` up from `0.2.2`).  It also came with pre-built wheel for the CUDA 11.5 that was installed on my system.

Downgrading CUDA to such an old version is not an option unfortunately :(

**Comment by markjlorenz** [comment]
No downgrade should be needed.  I started using a different machine image today that had CUDA 12.0 and using auto-gptq 0.4.2 got the job done again.

```
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
```
