### ISSUE TITLE
Installing localGPT on Windows

### ISSUE THREAD

**Issue by gcapnias** [PromtEngineer/localGPT#440]
I have watched several videos about localGPT. I want to install this tool in my workstation. Although, it seems impossible to do so in Windows.

```
(localGPT) PS D:\Users\Repos\localGPT> wmic os get BuildNumber,Caption,version
BuildNumber  Caption                   Version
22621        Microsoft Windows 11 Pro  10.0.22621
(localGPT) PS D:\Users\Repos\localGPT> python --version
Python 3.10.0
```

I used `minicoda` to create a virtual environment (localGPT) based on Python v3.10, as showcased in the video. I tried to install requirements, but it comes with the error:
```
Failed to build llama-cpp-python chroma-hnswlib
ERROR: Could not build wheels for llama-cpp-python, chroma-hnswlib, which is required to install pyproject.toml-based projects
```

I do understand that native code/wheels cannot be built due to lack of installation of Visual Studio. I do not wish to have to recreate a C++ building environment. It takes time and disk space, and I do not want to be expert in C++ to run an application to evaluate it.

I understand that you cannot have ready-made native images for all platforms, versions, and architectures that exist. Can you have full support for certain platforms and architectures so that the application can be fully evaluated? 

Thanks,
George J.

**Comment by PromtEngineer** [comment]
Hi @gcapnias you will need to install Visual Studio for this to work on Windows. My recommendation is to use this on Linux, if possible. There are windows specific dependencies that unfortunately we can't do anything about.

**Comment by aaltulea** [comment]
Install VS2019, not 2022, and "Desktop development with c++" workload and the script will work. I tried it on windows 11. You don't need to setup and c++ environments. You can uninstall VS2019 after building llama-cpp-python if you want to save space.

**Comment by gcapnias** [comment]
@PromtEngineer I managed to build localGPT in WSL2/WSLg. As soon AS WSL2 comes up, it has CUDA support, and it compiles like a charm. :smiley:

@aaltulea Thanks for the pointers! One can install Visual Studio 2017 Build tools via chocolatey (https://community.chocolatey.org/packages/visualstudio2017buildtools). If I go through this, I will post any findings...


Regards,
George J.

**Comment by chujb** [comment]
> Install VS2019, not 2022, and "Desktop development with c++" workload and the script will work. I tried it on windows 11. You don't need to setup and c++ environments. You can uninstall VS2019 after building llama-cpp-python if you want to save space.

@aaltulea , do you run the localGPT on CPU undoer windows 11 OS? I also try it but it fail and I get this problems:
https://github.com/PromtEngineer/localGPT/issues/713

there are two problems:
1, ModuleNotFoundError: No module named 'llama_cpp'
2, ImportError: Could not import llama-cpp-python library. Please install the llama-cpp-python library to use this embedding model: pip install llama-cpp-python
3, CMake configuration failed
4, ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

Do you meet the same problems?
