### ISSUE TITLE
Model file location 

### ISSUE THREAD

**Issue by Mer-one1** [PromtEngineer/localGPT#449]
While running run_localGPT.py, the model download fails every time, I have downloaded the model manually and I was wondering where is the folder location to I put the bin file in.

**Comment by PromtEngineer** [comment]
What type of model are you using? Assuming you are working with GGML/GGUF format models via LlamaCPP, you can just provide the model path [here](https://github.com/PromtEngineer/localGPT/blob/80a3ffcfe5a62c6131e64b43cb1996970d30c28d/run_localGPT.py#L51) in the `run_localGPT.py` file.
