### ISSUE TITLE
Trying databases other than Chroma as Chroma DB crashes with certain types of GPU

### ISSUE THREAD

**Issue by zzadiues3338** [PromtEngineer/localGPT#468]
Been testing localGPT on a variety of platforms.
Chroma worked with my local RTX 2070 and with tesla T4 on ec2 instance. 
However when I used a different, more powerful GPU (A10 or v100 on ec2) the chroma db crashes and gave error 'illegal instruction'
(see this https://github.com/chroma-core/chroma/issues/506).As a result both ingest.py and run..py scripts cant be run on anything 
other than t4s. 
Apparently its a well known bug with chroma db...

As workaround I am looking to use an alternative database like epsilla, weaviate or FAISS but so far ive been unable to do so. 
I am a beginner in this field. 
Have you tried using something other than Chroma with localGPT?

**Comment by ahmarey** [comment]
please check constants.py   carefully
You need to change the embeddings and which model to use for lower end gpus like 2070

**Comment by zzadiues3338** [comment]
> please check constants.py carefully You need to change the embeddings and which model to use for lower end gpus like 2070

@ahmarey hkunlp/sentence-transformer worked just fine for creating embeddings with 2070.
