### ISSUE TITLE
Having trouble loading GGUF model

### ISSUE THREAD

**Issue by YanaSSS** [PromtEngineer/localGPT#475]
I have tried to load this gguf model:
MODEL_ID = "s3nh/Photolens-llama-2-13b-langchain-chat-GGUF"
MODEL_BASENAME = "Photolens-llama-2-13b-langchain-chat.Q4_K_S.gguf"

Did not make any other changes in the code. But I got this error: 
***\localGPT\chatvenv\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in ***\localGPT\models. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
llama.cpp: loading model from ./models\models--s3nh--Photolens-llama-2-13b-langchain-chat-GGUF\snapshots\69c31b64aa7245831b5d315_½é╗▌cerror loading model: unknown (magic, version) combination: 46554747, 00000002; **is this really a GGML file?
llama_load_model_from_file: failed to load model**
Traceback (most recent call last):
  File "***localGPT\run_localGPT_v2.py", line 251, in <module>
    main()
    return self.main(*args, **kwargs)
  File "***\localGPT\chatvenv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "***\localGPT\chatvenv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "***\localGPT\chatvenv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "***\localGPT\run_localGPT_v2.py", line 221, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type="llama")
  File "***\localGPT\run_localGPT_v2.py", line 140, in retrieval_qa_pipline
    qa = RetrievalQA.from_chain_type(llm=llm,
  File "***\localGPT\chatvenv\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 100, in from_chain_type
    combine_documents_chain = load_qa_chain(
  File "***\localGPT\chatvenv\lib\site-packages\langchain\chains\question_answering\__init__.py", line 249, in load_qa_chain
    return loader_mapping[chain_type](
  File "***\localGPT\chatvenv\lib\site-packages\langchain\chains\question_answering\__init__.py", line 73, in _load_stuff_chain
    llm_chain = LLMChain(
  File "***\localGPT\chatvenv\lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by N1h1lv5** [comment]
> I have tried to load this gguf model: MODEL_ID = "s3nh/Photolens-llama-2-13b-langchain-chat-GGUF" MODEL_BASENAME = "Photolens-llama-2-13b-langchain-chat.Q4_K_S.gguf"
> 
> Did not make any other changes in the code. But I got this error: **_\localGPT\chatvenv\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in **_\localGPT\models. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations. To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development warnings.warn(message) llama.cpp: loading model from ./models\models--s3nh--Photolens-llama-2-13b-langchain-chat-GGUF\snapshots\69c31b64aa7245831b5d315_½é╗▌cerror loading model: unknown (magic, version) combination: 46554747, 00000002; **is this really a GGML file? llama_load_model_from_file: failed to load model** Traceback (most recent call last): File "_**localGPT\run_localGPT_v2.py", line 251, in main() return self.main(_args, **kwargs) File "**_\localGPT\chatvenv\lib\site-packages\click\core.py", line 1078, in main rv = self.invoke(ctx) File "**_\localGPT\chatvenv\lib\site-packages\click\core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "**_\localGPT\chatvenv\lib\site-packages\click\core.py", line 783, in invoke return __callback(_args, **kwargs) File "**_\localGPT\run_localGPT_v2.py", line 221, in main qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type="llama") File "**_\localGPT\run_localGPT_v2.py", line 140, in retrieval_qa_pipline qa = RetrievalQA.from_chain_type(llm=llm, File "**_\localGPT\chatvenv\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 100, in from_chain_type combine_documents_chain = load_qa_chain( File "_**\localGPT\chatvenv\lib\site-packages\langchain\chains\question_answering__init__.py", line 249, in load_qa_chain return loader_mapping[chain_type]( File "**_\localGPT\chatvenv\lib\site-packages\langchain\chains\question_answering__init__.py", line 73, in _load_stuff_chain llm_chain = LLMChain( File "_**\localGPT\chatvenv\lib\site-packages\langchain\load\serializable.py", line 74, in **init** super().**init**(**kwargs) File "pydantic\main.py", line 341, in pydantic.main.BaseModel.**init** pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain llm none is not an allowed value (type=type_error.none.not_allowed)

did you try : 
pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir ?

**Comment by YanaSSS** [comment]
Worked like a charm! Thank you!
