### ISSUE TITLE
How to load other model to inference?

### ISSUE THREAD

**Issue by fenixlam** [PromtEngineer/localGPT#506]
First of all, better update the requirements.txt as this.
llama-cpp-python==0.2.6
peft==0.5.0
auto-gptq==0.4.2
langchain==0.0.295
chromadb==0.4.10

I have tested it in google colab.
If the user's machine is using the old llama-cpp-python, they cannot load the gguf model. 

And the second thing: The gguf model only work on llama-2-7B-chat. 
I have tested other models such as nous-hermes-llama-2-7b.Q8_0.gguf, luna-ai-llama2-uncensored.Q8_0.gguf, wizard-mega-13B.Q8_0.gguf, Wizard-Vicuna-7B-Uncensored.Q8_0.gguf. All of these didn't work (response with empty answer, but the source document searching are correct.)
That means it is not possible to change other models? And the inference has stucked in the censorship problem as llama-2 is censored.

P.S> I compared it with old privateGPT, this time localGPT works with huge accuracy improved in llama-2-7B.

update: Fixed, I have removed the promptTemplate_type frag 'llama' in retrieval_qa_pipline to make other models work.

**Comment by WiktorLigeza** [comment]
did you just removed chain_type_kwargs={"prompt": prompt, "memory": memory}, from  RetrievalQA.from_chain_type?
It didnt work for me ;/
