### ISSUE TITLE
Chroma collection langchain contains fewer than 4 elements.

### ISSUE THREAD

**Issue by JoeFu** [PromtEngineer/localGPT#52]
Chroma collection langchain contains fewer than 4 elements.
C:\Python310\lib\site-packages\transformers\generation\utils.py:1255: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(

**Comment by PromtEngineer** [comment]
Can you provide more details one what you mean by 4 elements?

**Comment by JoeFu** [comment]
Not sure, just the error message on the screen.

**Comment by irshad001** [comment]
I am also getting the same warning. I have ingested a .csv file which has more than 100K observations with 6 columns.
Is there something gone wrong with the embeddings?
