### ISSUE TITLE
Cannot import name 'LlamaTokenizer' 

### ISSUE THREAD

**Issue by armbis** [PromtEngineer/localGPT#54]
Excuse me, I'm a newbie and I'm trying to use LocalGPT but I have this problem.
A thousand thanks!

(base) Armando@iMac-di-Martina ~ % python Documents/LocalGPT/run_localGPT.py
Traceback (most recent call last):
  File "/Users/Armando/Documents/LocalGPT/run_localGPT.py", line 7, in <module>
    from transformers import LlamaTokenizer, LlamaForCausalLM, pipeline
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (/Users/Armando/anaconda3/lib/python3.10/site-packages/transformers/__init__.py)
(base) Armando@iMac-di-Martina ~ %

**Comment by Allaye** [comment]
@armbis can you please show your code, it is difficult trying to understand what is happening.

**Comment by mindwellsolutions** [comment]
Try installing "transformers": 
pip install transformers
conda update transformers

I was personally able to resolve this error by running localGPT outside of conda.

**Comment by Swag19602** [comment]
If you still having problems with from transformers import LlamaForCausalLM, LlamaTokenizer try to install the package directly from github:

pip install git+https://github.com/huggingface/transformers
also don't forget to change the Tokenizer config file from LLaMATokenizer to LlamaTokenizer.

source: https://github.com/huggingface/transformers/issues/22222
closes #54
