### ISSUE TITLE
GPTQ not working

### ISSUE THREAD

**Issue by mohcineelharras** [PromtEngineer/localGPT#572]
 mohcine    localGPT   main ≡  ~1   localGPT 3.10.0   6.955s⠀   python run_localGPT.py                                                                          bash  CPU: 4.17% | RAM: 29/31GB   11:40:21 
2023-10-11 11:40:39,199 - INFO - run_localGPT.py:229 - Running on: cuda
2023-10-11 11:40:39,199 - INFO - run_localGPT.py:230 - Display Source Documents set to: False
2023-10-11 11:40:39,199 - INFO - run_localGPT.py:231 - Use history set to: False
2023-10-11 11:40:39,296 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-10-11 11:40:41,395 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-10-11 11:40:41,435 - INFO - run_localGPT.py:56 - Loading Model: TheBloke/Wizard-Vicuna-7B-Uncensored-GPTQ, on: cuda
2023-10-11 11:40:41,435 - INFO - run_localGPT.py:57 - This action can take a few minutes!
2023-10-11 11:40:41,435 - INFO - load_models.py:86 - Using AutoGPTQForCausalLM for quantized models
2023-10-11 11:40:41,619 - INFO - load_models.py:93 - Tokenizer loaded
Downloading model.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.52G/4.52G [01:21<00:00, 55.6MB/s]
2023-10-11 11:42:03,414 - INFO - _base.py:727 - lm_head not been quantized, will be ignored when make_quant.
2023-10-11 11:42:03,415 - WARNING - qlinear_old.py:16 - CUDA extension not installed.
2023-10-11 11:42:13,229 - INFO - modeling.py:799 - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
2023-10-11 11:42:15,503 - WARNING - fused_llama_mlp.py:306 - skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
Downloading (…)neration_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [00:00<00:00, 1.04MB/s]
The model 'LlamaGPTQForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'LlamaForCausalLM', 'CodeGenForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'ElectraForCausalLM', 'ErnieForCausalLM', 'FalconForCausalLM', 'GitForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'LlamaForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MistralForCausalLM', 'MptForCausalLM', 'MusicgenForCausalLM', 'MvpForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PersimmonForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'Speech2Text2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'XmodForCausalLM'].
2023-10-11 11:42:15,717 - INFO - run_localGPT.py:89 - Local LLM Loaded

Enter a query: hello
/home/mohcine/mambaforge/envs/localGPT/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.2` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

**Comment by Komal-99** [comment]
@mohcineelharras  Did you resolved the model 'LlamaGPTQForCausalLM' is not supported for text-generation .
I know this is just a warning, but my model is not generating any answer returning empty string.

**Comment by PGCJ** [comment]
same as! what can we do?

**Comment by PGCJ** [comment]
> @mohcineelharras Did you resolved the model 'LlamaGPTQForCausalLM' is not supported for text-generation . I know this is just a warning, but my model is not generating any answer returning empty string.

Hello ,I have a trouble same as you in this"LlamaGPTQForCausalLM". Do you resolve it?

**Comment by Komal-99** [comment]
@PGCJ @mohcineelharras  I resolved this error by using another model inspace of basebame as model safetensors ..making it none to download whole model.

but still returning none. 'empty string". After loading llm midel it doesn't create the embedding of questions and pass it to vector store to return the answer

**Comment by PGCJ** [comment]
> @PGCJ @mohcineelharras I resolved this error by using another model inspace of basebame as model safetensors ..making it none to download whole model.
> 
> but still returning none. 'empty string". After loading llm midel it doesn't create the embedding of questions and pass it to vector store to return the answer

Sounds like I have the same problem you do. It works that can return  --source but can not return answer. I try to change a model to do it, if it  work , i will share you. Wish you can too .

**Comment by PGCJ** [comment]
> @PGCJ @mohcineelharras I resolved this error by using another model inspace of basebame as model safetensors ..making it none to download whole model.
> 
> but still returning none. 'empty string". After loading llm midel it doesn't create the embedding of questions and pass it to vector store to return the answer

Maybe it work if you change 7B model, and your question must be accurately stated

**Comment by Komal-99** [comment]
> > @PGCJ @mohcineelharras I resolved this error by using another model inspace of basebame as model safetensors ..making it none to download whole model.
> > but still returning none. 'empty string". After loading llm midel it doesn't create the embedding of questions and pass it to vector store to return the answer
> 
> Maybe it work if you change 7B model, and your question must be accurately stated

Did your model generating answer now??
Because I don't think so 7B will work because I am using  13b   and if not giving accurate it should atleast give some answers but returning nothing

**Comment by PGCJ** [comment]
> > > @PGCJ @mohcineelharras I resolved this error by using another model inspace of basebame as model safetensors ..making it none to download whole model.
> > > but still returning none. 'empty string". After loading llm midel it doesn't create the embedding of questions and pass it to vector store to return the answer
> > 
> > 
> > Maybe it work if you change 7B model, and your question must be accurately stated
> 
> Did your model generating answer now?? Because I don't think so 7B will work because I am using 13b and if not giving accurate it should atleast give some answers but returning nothing

Yes, although it still produces empty answers to some of my questions. But if you are more accurate, you can reply.I used a 13B model and it  did not work,so I  switched to a 7B model, it works!luckily

**Comment by Komal-99** [comment]
Okay great!! 

I am facing this issue suddenly do you have any idea  about it ?

![IMG_20231020_110516 (1)](https://github.com/PromtEngineer/localGPT/assets/74819092/0da7ed2c-b9ff-4dbc-9748-d3876e9d549c)

**Comment by PGCJ** [comment]
> Okay great!!
> 
> I am facing this issue suddenly do you have any idea about it ?
> 
> ![IMG_20231020_110516 (1)](https://user-images.githubusercontent.com/74819092/276831451-0da7ed2c-b9ff-4dbc-9748-d3876e9d549c.jpg)

maybe your pytorch version is wrong, you can check it

**Comment by Komal-99** [comment]
Yesterday it was working , still trying to upgrade it
