### ISSUE TITLE
download the vicuna-7B model manually?

### ISSUE THREAD

**Issue by sinaxvo1** [PromtEngineer/localGPT#60]
hi
i have poor network
so i couldn't download pytorch and other models without disconnect several times
is there any way to download  vicuna-7B model with other apps (like IDM)
and put it in the files manually?

**Comment by vai** [comment]
![image](https://github.com/PromtEngineer/localGPT/assets/523886/31c6a246-6ea2-4348-8c8e-a99f9edc731f)
That's ... 
`https://huggingface.co/hkunlp/instructor-xl/resolve/ce48b213095e647a6c3536364b9fa00daf57f436/2_Dense/pytorch_model.bin`

**Comment by PromtEngineer** [comment]
Thanks @vai. @sinaxvo1 for target location, check out here: https://github.com/PromtEngineer/localGPT#:~:text=Pretrained%20models%20are,tranformers%20installation%20page.

**Comment by sinaxvo1** [comment]
@PromtEngineer 
i found the model files link in the run_localGPT.py https://huggingface.co/hkunlp/instructor-xl
if i download files and copy in C:\Users\username\.cache\huggingface\hub it well skip downloading?

**Comment by HmzaMalik** [comment]
Sure, after downloading files, run this following command in python.


from transformers import AutoConfig

config = AutoConfig.from_pretrained("/Path_to_your_downloaded_file_folder/vicuna-7B-1.1-HF/config.json")

it will create some files under:
C:/Users/username/.cache/huggingface/hub/models--TheBloke--vicuna-7B-1.1-HF/blobs/....

I have got this from: https://huggingface.co/docs/transformers/installation#fetch-models-and-tokenizers-to-use-offline
