### ISSUE TITLE
limited number of sources used to answer

### ISSUE THREAD

**Issue by sardosan** [PromtEngineer/localGPT#627]
Hi guys,

When I ask something, no matters what kind of model I use, localGPT generally tells me that the number of source documents used to answer is never bigger than 4 (4 source documents for each question ever).

Is it the same for you? I think this is a problem since I have a lot of file in the source documents.

Thank you

**Comment by sardosan** [comment]
Hey there,

it it the same for you all? For all of you, the system returns only 4 sources per question?

Thank you!

**Comment by PromtEngineer** [comment]
@sardosan you can change the number of source documents by modifying this [line](https://github.com/PromtEngineer/localGPT/blob/8cb7168aeb05cfd1224013f96a5644c5bb21f62e/run_localGPT.py#L129) as 
` retriever = db.as_retriever(search_kwargs={"k": 10})`

**Comment by sardosan** [comment]
Thank you so much!
