### ISSUE TITLE
Does anyone know how to configure to support HuggingFaceH4/zephyr-7b-beta?   

### ISSUE THREAD

**Issue by HamiguaLu** [PromtEngineer/localGPT#639]

**Comment by clearsitedesigns** [comment]
So Zerphry is based on mistral, I believe, so you can open up the templates file, and you should see a mistral type template. You just need to switch to using that, template, but you still need to configure to download the zephyr model. I'm a bit unsure on the full process to use the template, but I believe that's where to start

**Comment by HamiguaLu** [comment]
> So Zerphry is based on mistral, I believe, so you can open up the templates file, and you should see a mistral type template. You just need to switch to using that, template, but you still need to configure to download the zephyr model. I'm a bit unsure on the full process to use the template, but I believe that's where to start

Thanks for the reply,  yes I already followed the process,  just don't know whch model should download

https://huggingface.co/HuggingFaceH4/zephyr-7b-beta/tree/main

![image](https://github.com/PromtEngineer/localGPT/assets/12206531/97e56b08-25a2-4118-8eff-b252ae333550)

**Comment by laurafbec** [comment]
Hi @HamiguaLu!! Did you finally use Zephyr in localGPT?
Thanks

**Comment by HamiguaLu** [comment]
No, I gave up
Anyway, I  have managed to start it based on the demo from hg face, below attached file you can have a reference
[start_zephyr.zip](https://github.com/PromtEngineer/localGPT/files/13537640/start_zephyr.zip)

By the way,  from my test, both Mistral/Zephyr are not very useful compared with chatgpt, it's just a toy at least right now
