### ISSUE TITLE
Everytime i run python run_localGPT.py it require internet, is there any fix to use model locally

### ISSUE THREAD

**Issue by mkmittalofficial** [PromtEngineer/localGPT#640]
Hi,
 Everytime i run python run_localGPT.py it require internet, is there any fix to use model locally.
 
 If i run without internet its giving this error
 `(MaxRetryError("HTTPSConnectionPool(host='huggingface.co, port=433`

can anybody else faces this issue?

**Comment by clearsitedesigns** [comment]
You will need to download your model from the internet, before you can use it. There is a check to actually get the model in this case it's probably trying to download llama2 from hugginface. After it's cached locally you shouldn't see that.
