### ISSUE TITLE
AutoGPTQ must be updated to 0.6 for Mistral

### ISSUE THREAD

**Issue by BeniaminC** [PromtEngineer/localGPT#695]
Will throw errors that it does not support Mixtral if not updated.

To fix:
do not install via requirements.txt. The file seems to be outdated. Simply uninstall the previous version, then install the latest version.

`pip uninstall auto-gptq`
`pip install auto-gptq`

Tested on Windows 11 - WSL2 Ubuntu, and NVIDIA GPU.
MODEL_ID: TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ
MODEL_BASENAME = model.safetensors

It works after updating.

**Comment by BeniaminC** [comment]
I just realized I got the wrong model. "Mixtral" vs. "Mistral".

**Comment by PromtEngineer** [comment]
This was done in  #737
