### ISSUE TITLE
Compare the response time differences between 4xA100 and 8xH100

### ISSUE THREAD

**Issue by yirunwang** [PromtEngineer/localGPT#696]
I installed localGPT on two systems, one with 4xA100 GPU and the other with 8xH100 GPU. The test results show that the response time of the two systems is almost the same (10~20) seconds. It seems that 4xA100 is better, which is very strange!  Can anyone help explain this behavior? How can I improve? Thanks

**Comment by SaiAkhil066** [comment]
May I know which GPU can i use for this to get answer in just 5-10 sec? and please let me know the price ranges also

**Comment by PromtEngineer** [comment]
@yirunwang it might be dependent on the model you are using. If you are using a smaller model then it might not use all the available resources. I am interested which model are you trying?

**Comment by yirunwang** [comment]
@PromtEngineer 
the model is llama-2-7b-chat.Q4_K_M.gguf
<img width="950" alt="image" src="https://github.com/PromtEngineer/localGPT/assets/3538547/7193f4ac-09a7-4b64-ab52-1cb6c3948e07">

<img width="957" alt="image" src="https://github.com/PromtEngineer/localGPT/assets/3538547/9dac89be-8bb3-4ac7-95cd-f441bdff97f6">

The picture above is the background log for the same question. The left side is the 4xA100 system and the right side is the 8xH100 system. There are three indicators. The first two are that H100 is better, and the third one is that A100 is much better.

**Comment by yirunwang** [comment]
Please close this issue, it is because the synchronization overhead is higher than any potential speed gain.

**Comment by yirunwang** [comment]
solved.
