### ISSUE TITLE
What is the difference between this and PrivateGPT?

### ISSUE THREAD

**Issue by OneCodeToRuleThemAll** [PromtEngineer/localGPT#7]
Since there is no discussion tabs available, I wanted to ask the question above so as to choose what is more appropriate for me.

**Comment by PromtEngineer** [comment]
I will have a look at that. But to answer your question, this will be using your GPU for both embeddings as well as LLM. So will be substaintially faster than privateGPT. Also its using Vicuna-7B as LLM so in theory the responses could be better than GPT4ALL-J model (which privateGPT is using). Hope this helps.
