### ISSUE TITLE
Embdedings & Model files Location in local system.

### ISSUE THREAD

**Issue by SelvakumarTS** [PromtEngineer/localGPT#700]
Hi.. Thanks for the model. It works good in my personal computer. In my office system, i have an issue connecting to huggingface.co via the code. It gives some SSL certificate error. Tried to fix it with some options available, but no success. I am just wondering, can you let me know here the models are saved while i run it in my personal systems , so that i can transfer those embedding and model files to my office laptop and use it directly instead of trying to connect to huggingface.  Basically i need to load the embeddings from a local repo.

Instead of below code, is there any alternate to load the Embedings directly from local system
embeddings = HuggingFaceInstructEmbeddings(model_name=EMBEDDING_MODEL_NAME, model_kwargs={"device": device_type})

and any other code changes in run_localGPT.py

**Comment by SaiAkhil066** [comment]
I hope your having a proper internet connection, beacuse when you run (python run_locagpt.py), at first, embedding model (hkunlp/instructor-large) which is selected as default model, will be started downloading, after that you, the LLM will be downloaded, so after this process, you dont need any of the internet connections.
I hope this helps you, Reply if any problem occurs.

**Comment by Dafterfly** [comment]
By default, the HuggingFace models are downloaded to "C:\Users\[your user name]\.cache\huggingface\hub"

**Comment by lavericklavericklaverick** [comment]
thanks! that worked perfectly!
