### ISSUE TITLE
No module named click

### ISSUE THREAD

**Issue by DrekoDev** [PromtEngineer/localGPT#712]
Hi there ! 

I have troubles running ingest.py and I don't know why. I am currently running it on my Mac M1 (8GB RAM)

The error is simple:

Traceback (most recent call last):
  File "/Users/victor/Documents/LLM/LocalGPT/localGPT/ingest.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'

Everything went well when installing requirements.txt. Tried to force reinstall click but the issue didn't disappear. Mini Conda works also well.

Maybe someone could help ?

**Comment by RogerAllenDu** [comment]
The installation of click failed. Try pip install click separately or create a new requirements.txt with your desired imports
