### ISSUE TITLE
INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

### ISSUE THREAD

**Issue by phoenixvictory** [PromtEngineer/localGPT#722]
Hey All,

Following the installation instructions of Windows 10. The installation of all dependencies went smoothly. I have tried several different models but the problem I am seeing appears to be the somewhere in the instructor. I am using ingest.py with a device type cpu using the pre-existing source pdf. Unfortunately I am met with this error constantly, any ideas what this may be?

2024-01-29 16:30:49,880 - INFO - SentenceTransformer.py:110 - Load pretrained SentenceTransformer: hkunlp/instructor-large
Traceback (most recent call last):
  File "C:\Users\Phx\Documents\GitHub\Localgpt\ingest.py", line 181, in <module>
    main()
  File "C:\Users\Phx\.conda\envs\localGPT\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Phx\.conda\envs\localGPT\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Phx\.conda\envs\localGPT\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Phx\.conda\envs\localGPT\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Phx\Documents\GitHub\Localgpt\ingest.py", line 157, in main
    embeddings = HuggingFaceInstructEmbeddings(
  File "C:\Users\Phx\.conda\envs\localGPT\lib\site-packages\langchain\embeddings\huggingface.py", line 148, in __init__
    self.client = INSTRUCTOR(
  File "C:\Users\Phx\.conda\envs\localGPT\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 194, in __init__
    modules = self._load_sbert_model(
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

**Comment by ujwpi** [comment]
Specify v2.2.2 for Sentence Transformers in your requirements.txt, the latest version for it (v2.3.0) was released on 29th Jan and there seems to be a breaking change.

**Comment by phoenixvictory** [comment]
That certainly did the trick! Thank you for taking the time to provide clarity on this one!

**Comment by g1ra** [comment]
I have a same error here , and did trick setting in  requirements.txt  : 
```
sentence-transformers==2.2.2

```

**Comment by ujwpi** [comment]
PR raised for this issue, waiting for it to be reviewed.
@phoenixvictory can we keep this issue open till its been fixed.

**Comment by Phycotron** [comment]
I have a same error here :
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

**Comment by janas-adam** [comment]
had similar issue in latest version `2.6.0`, like mentioned above: with `2.2.2` works well

```
line 191, in __init__
    modules = self._load_sbert_model(
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'
```

**Comment by qsdhj** [comment]
I also get this error: 
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

My code is from the langchain doc:

```python
from langchain.embeddings import HuggingFaceInstructEmbeddings

model_name = "hkunlp/instructor-large"
model_kwargs = {'device': 'cpu'}
encode_kwargs = {'normalize_embeddings': True}
hf = HuggingFaceInstructEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)
```

**Comment by NebeyouMusie** [comment]
run `pip install sentence-transformers==2.2.2` then restart your kernel. It worked for me.

**Comment by EZZAH** [comment]
1) Install  pip install sentence-transformers==2.2.2
2) restart your kernel. 
3) Wait for few second 
4) Rerun 

from langchain_community.embeddings import HuggingFaceInstructEmbeddings
from InstructorEmbedding import INSTRUCTOR
instructembeddings= HuggingFaceInstructEmbeddings(model_name = "hkunlp/instructor-xl",
model_kwargs = {'device': 'cpu'}, encode_kwargs = {'normalize_embeddings': True})

**Comment by arhamaneeq** [comment]
Hi, I'm having a similar but brain wracking issue. Upon installing v2.2.2 of sentence_transformers, I get a new error thrown by `HuggingFaceInstructEmbeddings`

```console
ImportError: Dependencies for InstructorEmbedding not found.
```

**Comment by HK-Victor-AI** [comment]
> Hi, I'm having a similar issue after solving the `unexpected keyword argument` one OP has posted. Upon installing v2.2.2 of sentence_transformers, I get a new error thrown by `HuggingFaceInstructEmbeddings`
> 
> ImportError: Dependencies for InstructorEmbedding not found.

Don't downgrade to v2.2.2. This is a passive way to solve the problem and in today's context, it is not good to downgrade to this rather old version. The error  `unexpected keyword argument` is due to the subroutine INSTRUCTOR._load_sbert_model() is wrongly called by the sentence transformer. The sentence transformer has its own _load_sbert_model() but overwritten by INSTRUCTOR._load_sbert_model(). So you can just delete INSTRUCTOR._load_sbert_model() (in the file instructor.py of the InstructorEmbedding library module) and then everything will be fine.
