### ISSUE TITLE
Loading checkpoint shards fails. Leaked semaphore objects

### ISSUE THREAD

**Issue by cohencoo** [PromtEngineer/localGPT#73]
This issue occurs when running the run_localGPT.py file. 

I've tried both cpu and cuda devices, but still results in the same issue below when loading checkpoint shards. The warning itself can be suppressed, but the process still gets killed no matter what.

Would changing the model_id to another model help? Otherwise I cannot figure out what is causing this vague issue.

Loading checkpoint shards:   0%|                                                                                                      | 0/2 [00:00<?, ?it/s]zsh: killed     /Users/cohen/Downloads/localGPT-main/.venv/bin/python 
(.venv) cohen@cohens-mbp localGPT-main % /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by alfawal** [comment]
Python's memory usage goes ~33 GB and crashes with that error.

**Comment by vicendominguez** [comment]
same same ... 

MacOS Ventura 13.4 (22F66) + Python 3.11.3 + Apple M1 Pro 16 GB Ram

Smelling like something with the size of the model... no idea.

**Comment by subinsebastien** [comment]
**Same problem on my machine too...**

Software:

    System Software Overview:

      System Version: macOS 13.3.1 (a) (22E772610a)
      Kernel Version: Darwin 22.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 10 days, 10 hours, 33 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Model Number: MGN63HN/A
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 8 GB
      System Firmware Version: 8422.100.650
      OS Loader Version: 8422.100.650
      Activation Lock Status: Enabled

**Comment by penthoy** [comment]
GPT/DB
Loading checkpoint shards:   0%|                          | 0/2 [00:00<?, ?it/s]
Killed
same here, I'm on 64gb cpu ram and 16gb Vram, crashed only said "killed" I'm on ubuntu WSL

**Comment by johnm-starling** [comment]
For Mac users, try looking at the post I made in a related ticket and let me know if it helps.

https://github.com/PromtEngineer/localGPT/issues/25#issuecomment-1578921662
