### ISSUE TITLE
is it possible to use a previously downloaded HF .gguf file

### ISSUE THREAD

**Issue by cleesmith** [PromtEngineer/localGPT#730]
First, this app works great on a MacBook Pro M3 Max 128GB and for lots of transformers and LLM models.  One of the few RAG app's where I have been able to run it without the internet (well, once all of the models are downloaded), and using the terminal command "sudo pumas run" I can see it using 100% GPU (mps) during queries. 
So thank you so much, and for your videos on YouTube.

Since I seem to be trying new RAG or fine-tuning app's so often, I have a lot of existing GGUF files from Hugging Face previously downloaded.  Is there a way I/you/us can change this app to use any of those previous ".gguf" downloads.  As it is time consuming to download the same stuff over and over again. I did notice that the "models" folder has file types other than just a ".gguf" file ... is there a way to convert previously downloaded gguf into the layout used in your "models" folder. 

Please let me know and thanks again for this repo.

**Comment by PromtEngineer** [comment]
Thank you and glad you are finding this useful. I am not sure, in the snapshots folder under every model that is downloaded, there is the main gguf file. The code is using llama-cpp-python (python binding) to download the file. This might be doing the conversion under the hood. Will need to look into that.

**Comment by VerdonTrigance** [comment]
@cleesmith you may look at https://huggingface.co/docs/huggingface_hub/guides/manage-cache and setting HF_HOME environment variable. I personally did it and all my HF models are downloading there. But on windows it will keep warming you about symlinks and some other stuff. Anyway you may try it. You can also download huggingface-cli and manage downloads and cache from it.

**Comment by NitkarshChourasia** [comment]
@VerdonTrigance There is a PR done for using symlinks without any errors or bugs being shown.
You can look into it.
The title of the PR has symlink in it.
Thank you.

**Comment by randoentity** [comment]
@MoSedky I haven't used this in a while, but it looks like I wrote it down incorrectly. It should be MODELS_PATH: https://github.com/PromtEngineer/localGPT/blob/a1dea3becb8b1ae28a87369b1636c4c4a4501c27/constants.py#L20
