### ISSUE TITLE
Can localGPT support Chinese?

### ISSUE THREAD

**Issue by Yaqing2023** [PromtEngineer/localGPT#756]
I have installed localGPT successfully, then I put seveal PDF files under SOURCE_DOCUMENTS directory, ran ingest.py without errro. Then i execute "python run_localGPT.py", enter a query in Chinese, the Answer is weired:
> Answer:

1
1
1

，

Anyone know how to make it work with Chinese？ thanks

**Comment by PromtEngineer** [comment]
Which model are you using? In this case, you will need to ensure both the embedding model that you select as well as the LLM is multi-lingual.

**Comment by Yaqing2023** [comment]
i use EMBEDDING_MODEL_NAME = "hkunlp/instructor-xl, 
MODEL_ID = "TheBloke/openbuddy-mistral-7B-v13.1-GGUF"
MODEL_BASENAME = "openbuddy-mistral-7b-v13.1.Q4_K_M.gguf"

somehow this works fine now, but i need to make a little change in ingest.py 
def detect_file_encoding(file_path):
    with open(file_path, 'rb') as f:
        result = chardet.detect(f.read())
    return result['encoding']

in load_single_document, 
            file_encoding = detect_file_encoding(file_path)  #find the encoding type
            loader = loader_class(file_path,encoding=file_encoding)
otherwise it won't load chinese files properly

**Comment by greagain** [comment]
Can you share your ingest.py code that makes Chinese working, I am not sure where to put the code you have provided, I tried a little bit, but it's not working?

Besides, other than set:
EMBEDDING_MODEL_NAME = "hkunlp/instructor-xl,
MODEL_ID = "TheBloke/openbuddy-mistral-7B-v13.1-GGUF"
MODEL_BASENAME = "openbuddy-mistral-7b-v13.1.Q4_K_M.gguf"
and change ingest.py, did you make any other changes to get Chinese work?

**Comment by Yaqing2023** [comment]
@greagain in ingest.py, you need to add import chardet, right after that add 
def detect_file_encoding(file_path):
    with open(file_path, 'rb') as f:
        result = chardet.detect(f.read())
    return result['encoding']

then in def load_single_document(file_path: str) -> Document:, change change loader_class to 
        if loader_class:
            file_log(file_path + " loaded.")
            file_encoding = detect_file_encoding(file_path)  #find the encoding type
            loader = loader_class(file_path,encoding=file_encoding)

no other changes. 
The simple way to verify is to query the chroma db directly to see whether it returns chinese correctly or not.  For example, after ingest.py, it will create a DB persistence, then run following

from langchain.vectorstores import Chroma
from utils import get_embeddings
embeddings = get_embeddings('cpu')
print(embeddings)

db = Chroma(persist_directory="path_to_your_persistence_DB", embedding_function = embeddings)
query = "some chhinese string to query"
docs = db.similarity_search(query,k=5)  #返回5条
print(docs[0].page_content)

**Comment by greagain** [comment]
Thanks. Just tried and it is working, though the results is really 'meh', much worse that for English.
