### ISSUE TITLE
ingest.py is not supporting multi cores

### ISSUE THREAD

**Issue by MSZ-MGS** [PromtEngineer/localGPT#76]
ingest.py is not supporting multi cores.

**Comment by su77ungr** [comment]
I'm repeating myself regarding those low-effort forks of privateGPT: just use [CASALIOY](https://github.com/su77ungr/CASALIOY). It's faster and solves the issues those repos won't fix.

**Comment by Tchekda** [comment]
Same issue here, tried to import 400 pdf and it took a while because using only 1 core. 
I might make a PR to fix this but if someone wants to do it, go ahead
