### ISSUE TITLE
Autoawq

### ISSUE THREAD

**Issue by testercell** [PromtEngineer/localGPT#777]
When installing the requirements I hit the following:
ERROR: Could not find a version that satisfies the requirement autoawq (from versions: none)
ERROR: No matching distribution found for autoawq

I do have an nvidia GPU w/cuda version of 12.4 so I'm not entirely sure  what the issue is

**Comment by tail-3lbs** [comment]
How to solve this please?

**Comment by testercell** [comment]
Build from source made it work for me
