### ISSUE TITLE
Cannot access gated repo

### ISSUE THREAD

**Issue by mishraaditya595** [PromtEngineer/localGPT#799]
I am running locally LocalGPT on my Apple M1 Macbook Air.
Using these 

LLAMA 3 # use for Apple Silicon
MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
MODEL_BASENAME = None

I am getting this error when I run it:
`
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct.
401 Client Error. (Request ID: Root=1-664b1557-4cd13d101e705c317e4ea941;d1df1237-5cab-403a-8ae5-a00448512049)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted. You must be authenticated to access it.
`

I am not using docker. How can I run it?

**Comment by edwardak** [comment]
Install `huggingface-cli` and download the model!

**Comment by mishraaditya595** [comment]
Thanks @edwardak.
