### ISSUE TITLE
How can I uninstall this?

### ISSUE THREAD

**Issue by Devesh-N** [PromtEngineer/localGPT#89]
I just ran those .py files as instructed in the README.md file. After that, a bunch of stuff was downloaded. It took up a ton of space in my system. I want to uninstall it now as my system cannot handle the space and is low configuration.
Configuration of my mini PC:
32 GB ram
RTX 3070
Ryzen 9  5900x 24 cores

**Comment by StrangeNPC** [comment]
You can delete the files from your .cache directory that was downloaded.

**Comment by vicendominguez** [comment]
in your $HOME in (MacOS at lease)

**Comment by psegovias** [comment]
pip uninstall -r requirements.txt

**Comment by jose-otero-rodriguez** [comment]
I use "huggingface-cli delete-cache" to select the models that I want to delete

**Comment by Devesh-N** [comment]
huggingface-cli delete-cache worked for me!
