### ISSUE TITLE
Model returns blank answers

### ISSUE THREAD

**Issue by naorsabag** [PromtEngineer/localGPT#93]
Also got the following related warning:

`Input length of input_ids is 2326, but `max_length` is set to 2048. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.`

How can I increase `max_new_tokens` or alternatively reset the current session?

**Comment by PromtEngineer** [comment]
You probably want to reduce the number of chunks returned by the model. You can set `db.as_retriever(search_kwargs={"k": 3})` on this [line](https://github.com/PromtEngineer/localGPT/blob/e4826e7e72723d87790067f19c72c53d03256e2b/run_localGPT.py#LL73C10-L73C10). Play around with value of `k`
